/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package check;

import exammap.Exam;
import exammap.Exammap;
import java.awt.Color;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import org.apache.commons.io.FilenameUtils;
import properties.P;

/**
 *
 * @author Piyapong
 */
public class Examcheck extends javax.swing.JFrame {

    /**
     * Creates new form Examcheck
     */
    public Examcheck() {
        initComponents();
        setTitle("โปรแกรมตราวสอบไฟล์ข้อสอบ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1202, 610));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 810));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText(" 1. Choose Doc folder ");
        jLabel2.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);

        jButton1.setText(" Browse ");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 10000));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2);

        jPanel5.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel5.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText(" Folder directory");
        jLabel4.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4);

        jPanel1.add(jPanel5);

        jPanel3.setLayout(new java.awt.GridLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText(" Results:");
        jLabel3.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3);

        jButton2.setText("Check");
        jButton2.setEnabled(false);
        jButton2.setMaximumSize(new java.awt.Dimension(100, 10000));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 0));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Choose doc folder
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose a folder that contains doc files.");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jLabel4.setText(chooser.getSelectedFile().getAbsolutePath());
            jLabel4.setBackground(Color.green);
            P.DOCFILEPATH = jLabel4.getText();
            jButton2.setEnabled(true);
            
        }
        else {
            jButton2.setEnabled(false);
            //System.out.println("No Selection ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jTextArea1.setText("");
        
        File docfolder = new File(P.DOCFILEPATH);

        File[] filelist = docfolder.listFiles(new DocFileFilter());
        int warning = 0;
            for(int i=0;i<filelist.length;i++)
            {
                String filename = FilenameUtils.removeExtension(filelist[i].getName());
                check c = new check();
                ArrayList list = c.read(filelist[i]);
                if(list.size()==0)
                {
                    append(filename+" complete");
                }
                else
                {
                    for(int j=0;j<list.size();j++)
                    {
                        append(filename+" "+list.get(j).toString());
                        warning++;
                    }
                }
            }
        
        jLabel3.setText(" Result: Complete "+filelist.length+" Warning "+warning);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examcheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examcheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examcheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examcheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examcheck().setVisible(true);
            }
        });
    }

    private void append(String text)
    {
        jTextArea1.append(text+"\n");
    }
    public class DocFileFilter implements FileFilter
    {
    private final String[] okFileExtensions =
        new String[] {"docx"};

        @Override
    public boolean accept(File file)
    {
        for (String extension : okFileExtensions)
        {
        if (file.getName().toLowerCase().endsWith(extension))
        {
            return true;
        }
        }
        return false;
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
