/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import exam.Detail;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import main.Mainframe;
import properties.P;

/**
 *
 * @author bon
 */
public class Settingviewer extends javax.swing.JFrame {

    Detail d;
    public Settingviewer() {
        initComponents();
        /*
        jLabel7.setText("/home/bon/NetBeansProjects/Examwifiserver/Doc file");
        jLabel4.setText("/home/bon/NetBeansProjects/Examwifiserver/Excel file/set.xls");
        
        P.DOCFILEPATH = jLabel7.getText();
        P.EXCELPATH = jLabel4.getText();
        
        Detail d = new Detail();
        String result = d.getDetail();
        jLabel8.setText(result);
        jLabel8.setBackground(Color.green);
        * 
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(124, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(643, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exam viewer");
        jLabel1.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText(" 1. Choose Doc folder ");
        jLabel2.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);

        jButton1.setText(" Browse ");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 10000));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);

        jPanel5.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel5.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setBackground(java.awt.Color.darkGray);
        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel8.setOpaque(true);
        jPanel5.add(jLabel8);

        getContentPane().add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText(" 2. Choose Excel file");
        jLabel3.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3);

        jButton2.setText(" Browse ");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 10000));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 0));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        getContentPane().add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setBackground(java.awt.Color.darkGray);
        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel7.setOpaque(true);
        jPanel3.add(jLabel7);

        getContentPane().add(jPanel3);

        jPanel6.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText(" 3. Load exam");
        jLabel5.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel5.setOpaque(true);
        jPanel6.add(jLabel5);

        jButton3.setText(" Load");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 10000));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 0));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        getContentPane().add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(100000, 30));
        jPanel7.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setBackground(java.awt.Color.darkGray);
        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(12400, 43));
        jLabel9.setOpaque(true);
        jPanel7.add(jLabel9);

        getContentPane().add(jPanel7);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(124, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(643, 50));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton4.setText("GO");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setEnabled(false);
        jButton4.setMaximumSize(new java.awt.Dimension(72000, 55));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);

        getContentPane().add(jPanel8);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Choose doc folder
        JFileChooser chooser = new JFileChooser(); 
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("Choose a folder that contains doc files.");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    //
    // disable the "All files" option.
    //
    chooser.setAcceptAllFileFilterUsed(false);
    //    
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
        jLabel8.setText(chooser.getSelectedFile().getAbsolutePath());
        jLabel8.setBackground(Color.green);
        P.DOCFILEPATH = jLabel8.getText();
        //jButton4.setEnabled(true);
      }
    else {
      //System.out.println("No Selection ");
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!P.DOCFILEPATH.equals("") && d!=null)
        {
            Mainviewer main = new Mainviewer();
            main.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Choose an excel file

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose an excel file.");
        FileFilter filter = new Excelfilefilter(".xls", new String[]{"xls"});
        chooser.setFileFilter(filter);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jLabel7.setText(chooser.getSelectedFile().getAbsolutePath());
            jLabel7.setBackground(Color.green);
            P.EXCELPATH = jLabel7.getText();
        } else {
            //System.out.println("No Selection ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        d = new Detail();
        String result = d.getDetail();
        if (result.equals("complete")) {
            jLabel9.setText(result);
            jLabel9.setBackground(Color.green);
            jButton4.setEnabled(true);
        } else {
            jLabel9.setText(result);
            jLabel9.setBackground(Color.yellow);
            jButton4.setEnabled(false);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settingviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settingviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settingviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settingviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Settingviewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
