/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import exammap.Exam;
import exammap.Exammap;
import java.awt.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import properties.P;

/**
 *
 * @author bon
 */
public class Viewer extends javax.swing.JFrame {

    /**
     * Creates new form Viewer
     */
    Font f = new Font("SansSerif", Font.PLAIN, 12);
    int width = 376;
    JPanel[] choice = new JPanel[5];

    int select = 0;
    public Viewer(Exam ex) {
        initComponents();
        
        choice[0] = jPanel22;
        choice[1] = jPanel24;
        choice[2] = jPanel26;
        choice[3] = jPanel28;
        choice[4] = jPanel30;

        if(ex!=null)
        {
            jLabel2.setText(ex.getexamID());
            //System.out.println(ex.getexamID());
            addContent(jPanel10, ex.getQuestiondetails(), ex.getQuestionstyle());
            ArrayList choicearray = ex.getChoicedetails();
            //System.out.println("---------------------");
            for(int i=0;i<choicearray.size();i++)
            {
                ArrayList choicecontent = (ArrayList)choicearray.get(i);
                addContent(choice[i], choicecontent, (ArrayList)ex.getChoicestyle().get(i));
            }
            //System.out.println("---------------------");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 640));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setPreferredSize(new java.awt.Dimension(400, 640));
        jPanel14.setLayout(new java.awt.GridLayout());

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(400, 640));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(400, 640));

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 640));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 640));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(12, 640));
        jPanel2.setMinimumSize(new java.awt.Dimension(12, 640));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(376, 640));
        jPanel3.setMinimumSize(new java.awt.Dimension(376, 640));
        jPanel3.setName("");
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(376, 640));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(376, 77));
        jPanel7.setMinimumSize(new java.awt.Dimension(376, 77));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(376, 77));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7);

        jPanel8.setBackground(java.awt.Color.gray);
        jPanel8.setMaximumSize(new java.awt.Dimension(376, 18));
        jPanel8.setMinimumSize(new java.awt.Dimension(376, 18));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setBackground(java.awt.Color.red);
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(240, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(240, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(240, 17));
        jPanel8.add(jLabel2);

        jPanel6.add(jPanel8);

        jPanel9.setBackground(java.awt.Color.lightGray);
        jPanel9.setMaximumSize(new java.awt.Dimension(376, 1000));
        jPanel9.setMinimumSize(new java.awt.Dimension(376, 20));
        jPanel9.setPreferredSize(new java.awt.Dimension(376, 20));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(376, 0));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 12, 5));
        jPanel9.add(jPanel10);

        jPanel6.add(jPanel9);

        jPanel11.setMaximumSize(new java.awt.Dimension(376, 20));
        jPanel11.setMinimumSize(new java.awt.Dimension(376, 20));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jPanel22.setOpaque(false);
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 12, 5));
        jPanel11.add(jPanel22);

        jPanel6.add(jPanel11);

        jPanel12.setBackground(java.awt.Color.lightGray);
        jPanel12.setMaximumSize(new java.awt.Dimension(376, 1));
        jPanel12.setMinimumSize(new java.awt.Dimension(376, 1));
        jPanel12.setPreferredSize(new java.awt.Dimension(376, 1));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel12);

        jPanel23.setMaximumSize(new java.awt.Dimension(376, 20));
        jPanel23.setMinimumSize(new java.awt.Dimension(376, 20));
        jPanel23.setOpaque(false);
        jPanel23.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jPanel24.setOpaque(false);
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 12, 5));
        jPanel23.add(jPanel24);

        jPanel6.add(jPanel23);

        jPanel17.setBackground(java.awt.Color.lightGray);
        jPanel17.setMaximumSize(new java.awt.Dimension(376, 1));
        jPanel17.setMinimumSize(new java.awt.Dimension(376, 1));
        jPanel17.setPreferredSize(new java.awt.Dimension(376, 1));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel17);

        jPanel25.setMaximumSize(new java.awt.Dimension(376, 20));
        jPanel25.setMinimumSize(new java.awt.Dimension(376, 20));
        jPanel25.setOpaque(false);
        jPanel25.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel25.setLayout(new java.awt.GridLayout(1, 0));

        jPanel26.setOpaque(false);
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 12, 5));
        jPanel25.add(jPanel26);

        jPanel6.add(jPanel25);

        jPanel18.setBackground(java.awt.Color.lightGray);
        jPanel18.setMaximumSize(new java.awt.Dimension(376, 1));
        jPanel18.setMinimumSize(new java.awt.Dimension(376, 1));
        jPanel18.setPreferredSize(new java.awt.Dimension(376, 1));
        jPanel18.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel18);

        jPanel27.setMaximumSize(new java.awt.Dimension(376, 20));
        jPanel27.setMinimumSize(new java.awt.Dimension(376, 20));
        jPanel27.setOpaque(false);
        jPanel27.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel27.setLayout(new java.awt.GridLayout(1, 0));

        jPanel28.setOpaque(false);
        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 12, 5));
        jPanel27.add(jPanel28);

        jPanel6.add(jPanel27);

        jPanel19.setBackground(java.awt.Color.lightGray);
        jPanel19.setMaximumSize(new java.awt.Dimension(376, 1));
        jPanel19.setMinimumSize(new java.awt.Dimension(376, 1));
        jPanel19.setPreferredSize(new java.awt.Dimension(376, 1));
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel19);

        jPanel29.setMaximumSize(new java.awt.Dimension(376, 20));
        jPanel29.setMinimumSize(new java.awt.Dimension(376, 20));
        jPanel29.setOpaque(false);
        jPanel29.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel29.setLayout(new java.awt.GridLayout(1, 0));

        jPanel30.setOpaque(false);
        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 12, 5));
        jPanel29.add(jPanel30);

        jPanel6.add(jPanel29);

        jPanel20.setBackground(java.awt.Color.lightGray);
        jPanel20.setMaximumSize(new java.awt.Dimension(376, 1));
        jPanel20.setMinimumSize(new java.awt.Dimension(376, 1));
        jPanel20.setPreferredSize(new java.awt.Dimension(376, 1));
        jPanel20.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel20);

        jPanel21.setMaximumSize(new java.awt.Dimension(376, 70000));
        jPanel21.setMinimumSize(new java.awt.Dimension(376, 0));
        jPanel21.setOpaque(false);
        jPanel21.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel21.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel21);

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(12, 640));
        jPanel4.setMinimumSize(new java.awt.Dimension(12, 640));
        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        jPanel1.setBounds(0, 0, 400, 640);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel5.setMaximumSize(new java.awt.Dimension(400, 640));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 640));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewer/blank.png"))); // NOI18N
        jPanel5.add(jLabel1);

        jPanel5.setBounds(0, 0, 400, 640);
        jLayeredPane1.add(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel14.add(jLayeredPane1);

        getContentPane().add(jPanel14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Viewer(null).setVisible(true);
            }
        });
    }
    
    private void addContent(JPanel panel, ArrayList list, ArrayList stylelist)
    {
        //ArrayList questionarray = ex.getQuestiondetails();
        int h = 0;
        for(int i=0;i<list.size();i++)
        {
            //panel.setBackground(Color.white);
            //panel.setLayout(new GridLayout());
            //JLabel label = new JLabel();
            //String t = String.format("<html><div WIDTH=%d>%s</div><html>", width, questionarray.get(i).toString());
            JLabel label = new JLabel();
            
            //label.setMinimumSize(new Dimension(100,18));
            //label.setPreferredSize(new Dimension(100,30));
            //label.setMaximumSize(new Dimension(100,500));
            //String t = questionarray.get(i).toString();
            //label.setMaximumSize(new Dimension(500,1000));
            //label.setPreferredSize(new Dimension(500,100));
            switch (list.get(i).getClass().getName()) {
                case "java.lang.String":
                    //label.setText("<html>"+questionarray.get(i).toString()+"</html>");
                    //ArrayList stylelist = (ArrayList)(ex.getQuestionstyle().get(i));
                    
                    //label = new Textpanel(slist);
                    ArrayList slist = (ArrayList)(stylelist.get(i));
                    label = new Textpanel(slist);
                    label.setText(list.get(i).toString());
                    Graphics g = this.getGraphics();
                    FontMetrics metrics = g.getFontMetrics(f);
                    int adv = metrics.stringWidth(list.get(i).toString());
                    //int n = metrics.getHeight()*(adv/(width)+1);
                    
                    BigDecimal b1 = new BigDecimal(adv);
                    BigDecimal b2 = new BigDecimal(width);
                    int n = metrics.getHeight()*b1.divide(b2,0,RoundingMode.CEILING).intValue();
                    //System.out.println(""+i+" "+(adv/(width))+" "+b1.divide(b2,3,RoundingMode.CEILING)+" "+b1.divide(b2,0,RoundingMode.CEILING).intValue());
                    label.setPreferredSize(new Dimension(width, n));
                    h = h+n;
                    break;
                case "[B":
                    label = new JLabel();
                    ImageIcon imageIcon = new ImageIcon((byte[])list.get(i));
                    Image image = imageIcon.getImage(); // transform it 
                    Image newimg = image.getScaledInstance(imageIcon.getIconWidth()*25/100, imageIcon.getIconHeight()*25/100,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
                    label.setIcon(new ImageIcon(newimg));
                    h = h +10+(imageIcon.getIconHeight()*25/100);
                    break;
            }
            label.setFont(f);
            panel.add(label); 
        }
        panel.setPreferredSize(new Dimension(panel.getWidth(),h));
        JPanel p = (JPanel)panel.getParent();
        p.setPreferredSize(new Dimension(panel.getWidth(),h+10));
    }
    public JPanel getQuestionpanel()
    {
        return jPanel10;
    }
    public JPanel[] getChoicepanel()
    {
        return choice;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
