/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import table.Record;

/**
 *
 * @author bon
 */
public class progress extends javax.swing.JFrame {

    Socket socket;
    Mainframe main;
    String survey;
    Record record;
    int total;
    public progress(Mainframe main, String survey, Record record) {
        initComponents();
        this.main = main;
        this.survey = survey;
        this.record = record;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 60));
        setMinimumSize(new java.awt.Dimension(430, 60));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setMaximumSize(new java.awt.Dimension(430, 60));
        jPanel5.setMinimumSize(new java.awt.Dimension(430, 60));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(430, 60));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setMaximumSize(new java.awt.Dimension(110, 3000));
        jPanel1.setMinimumSize(new java.awt.Dimension(110, 30));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(110, 30));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0000000000");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel1);

        jPanel6.add(jPanel1);

        jPanel17.setMaximumSize(new java.awt.Dimension(10, 60));
        jPanel17.setMinimumSize(new java.awt.Dimension(10, 60));
        jPanel17.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel6.add(jPanel17);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(106, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(120, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(120, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ready");
        jLabel2.setMaximumSize(new java.awt.Dimension(81, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(81, 30));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(81, 30));
        jPanel3.add(jLabel2);

        jPanel2.add(jPanel3);

        jPanel13.setMaximumSize(new java.awt.Dimension(10, 60));
        jPanel13.setMinimumSize(new java.awt.Dimension(10, 60));
        jPanel13.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel2.add(jPanel13);

        jButton1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton1.setText("start");
        jButton1.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel14.setMaximumSize(new java.awt.Dimension(10, 60));
        jPanel14.setMinimumSize(new java.awt.Dimension(10, 60));
        jPanel14.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel2.add(jPanel14);

        jButton2.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton2.setText("stop");
        jButton2.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jPanel15.setMaximumSize(new java.awt.Dimension(10, 60));
        jPanel15.setMinimumSize(new java.awt.Dimension(10, 60));
        jPanel15.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel2.add(jPanel15);

        jPanel6.add(jPanel2);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);
        jPanel7.add(jProgressBar1);

        jPanel5.add(jPanel7);

        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        startExam();
        Object[] ob = {"START",jLabel1.getText()};
         record.insertData(ob);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        forcestopExam();
        Object[] ob = {"STOP",jLabel1.getText()};
         record.insertData(ob);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new progress(null,null,null).setVisible(true);
            }
        });
    }
    public void setSocket(Socket socket)
    {
        this.socket = socket;
    }
    public void setRegisteredstatus()
    {
        jLabel2.setText("register");
        jLabel2.setBackground(Color.blue);
    }
    public void setDeactivatestatus()
    {
        jLabel2.setText("deactivate");
        jLabel2.setBackground(Color.darkGray);
    }
    public void startExam()
    {
        if(socket!=null && !socket.isClosed())
            {
            try {
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                Object[] value = {"START",timeStringtoInt(main.getTimelabel().getText())};
                out.writeObject(value);
                out.flush();
                setStartstatus();
                //out.close();
                }
                catch (IOException e){
                    setDisconnectedstatus();
                    e.printStackTrace(System.err);
                }
            }
    }
    public void updateTime()
    {
        if(socket!=null && !socket.isClosed())
            {
            try {
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                Object[] value = {"TIME",timeStringtoInt(main.getTimelabel().getText())};
                out.writeObject(value);
                out.flush();
                //out.close();
                }
                catch (IOException e){
                    setDisconnectedstatus();
                    e.printStackTrace(System.err);
                }
            }
    }
    /*
    public void forcestopExam()
    {
        if(socket!=null && !socket.isClosed())
            {
            try {
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                String[] value = new String[1];
                if(survey.equals("yes") && !jLabel2.getText().equals("survey"))
                {
                    value[0] = "SURVEY";
                }
                else
                {
                    value[0] = "STOP";
                }
                out.writeObject(value);
                out.flush();
                //out.close();
                if(value[0].equals("SURVEY"))
                {
                    setSurveystatus();
                }
                else if(value[0].equals("STOP"))
                {
                    setStopstatus();
                }
                
                }
                catch (IOException e){
                    setDisconnectedstatus();
                    e.printStackTrace(System.err);
                }
            }
    }
    * 
    */
    public void forcestopExam()
    {
        if(socket!=null && !socket.isClosed())
            {
                //if(jLabel2.getText().equals("start"))
                //{
            try {
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                /*String[] value = new String[1];
                if(survey.equals("yes") && !jLabel2.getText().equals("survey"))
                {
                    value[0] = "SURVEY";
                }
                else
                {
                    value[0] = "STOP";
                }*/
                String[] value = {"STOP"};
                out.writeObject(value);
                out.flush();
                //out.close();
                /*
                if(value[0].equals("SURVEY"))
                {
                    setSurveystatus();
                }
                else if(value[0].equals("STOP"))
                {
                    setStopstatus();
                }
                */
                setStopstatus();
                }
                catch (IOException e){
                    setDisconnectedstatus();
                    e.printStackTrace(System.err);
                }
            //}
            }
    }
    public void stopExam()
    {
        if(socket!=null && !socket.isClosed() && !jLabel2.getText().equals("disconnect"))
            {
                //if(jLabel2.getText().equals("start"))
                //{
            try {
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                /*String[] value = new String[1];
                if(survey.equals("yes") && !jLabel2.getText().equals("survey"))
                {
                    value[0] = "SURVEY";
                }
                else
                {
                    value[0] = "STOP";
                }*/
                String[] value = {"SURVEY"};
                out.writeObject(value);
                out.flush();
                //out.close();
                /*
                if(value[0].equals("SURVEY"))
                {
                    setSurveystatus();
                }
                else if(value[0].equals("STOP"))
                {
                    setStopstatus();
                }
                */
                if(survey.equals("yes") && jLabel2.getText().equals("start"))
                {
                    setSurveystatus();
                }

                }
                catch (IOException e){
                    setDisconnectedstatus();
                    e.printStackTrace(System.err);
                }
            //}
            }
    }
    public void setStartstatus()
    {
        if(!jLabel2.getText().equals("disconnect"))
        {
            jLabel2.setText("start");
            jLabel2.setBackground(Color.green);
        }
    }
    public void setSurveystatus()
    {
        jLabel2.setText("survey");
        jLabel2.setBackground(Color.white);
    }
    public void setSubmitstatus()
    {
        jLabel2.setText("submit");
        jLabel2.setBackground(Color.cyan);
    }
    public void setStopstatus()
    {
        jLabel2.setText("stop");
        jLabel2.setBackground(Color.yellow);
    }
    public void setDisconnectedstatus()
    {
        jLabel2.setText("disconnect");
        jLabel2.setBackground(Color.red);
    }
    public void setStudentID(String id)
    {
        jLabel1.setText(id);
    }
    public void setTotal(int total)
    {
        this.total = total;
    }
    public void setProgression(int done)
    {
        jProgressBar1.setMaximum(total);
        jProgressBar1.setValue(done);
        jProgressBar1.setString(""+done+"/"+total);
    }
    private int timeStringtoInt(String time)
    {
        int second = (Integer.parseInt(time.substring(0, 2))*3600)+(Integer.parseInt(time.substring(3, 5))*60)+(Integer.parseInt(time.substring(6, 8)));
        return second;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
